plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.worldexecute.viewer"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.worldexecute.viewer"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        resourceConfigurations += listOf("zh", "en")
    }

    signingConfigs {
        /* A release build that anyone can install needs a key, and shipping a
           throwaway debug key is the honest version of "unsigned". */
        create("shared") {
            storeFile = file("signing/shared.jks")
            storePassword = "worldexecute"
            keyAlias = "worldexecute"
            keyPassword = "worldexecute"
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
        release {
            isMinifyEnabled = false
            isShrinkResources = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("shared")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    /* The film's MP3 is 8 MB of already-compressed audio; deflating it again
       costs build time and saves nothing. The text assets are stored plain so
       the asset copy stays a straight file copy. */
    androidResources {
        noCompress += listOf("mp3", "js", "css", "html", "json")
    }

    packaging {
        resources.excludes += setOf(
            "META-INF/*.kotlin_module",
            "META-INF/DEPENDENCIES",
            "META-INF/LICENSE*",
            "kotlin/**"
        )
    }

    buildFeatures {
        buildConfig = true
    }

    /* `AssetServerTest` starts the real socket server, and starting it writes a
       line through `Diag`, which writes through `android.util.Log`. Under a JVM
       test the stub `Log` throws by default, so the server could not be started
       at all. Returning default values turns those calls into no-ops — the log
       is not what the test is looking at. */
    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    lint {
        abortOnError = false
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.2")

    /* The QR code on the LAN share screen. This is zxing's plain-JVM encoder:
       `zxing-android-embedded` would pull in an activity and a camera permission
       for a job that is one function call, and the app never scans anything. */
    implementation("com.google.zxing:core:3.5.3")

    /* JVM-only tests. The two things worth testing here — that a QR round-trips
       through a decoder, and that a wrong share token cannot reach a file — are
       both pure logic with no Android in them, so they need no device. */
    testImplementation("junit:junit:4.13.2")
}

/* ============================================================================
   The film in `app/src/main/assets/web` is GENERATED by `tools/build-web-assets.mjs`;
   it is not the film in the repository root and it is not edited by hand. The
   two live in different directories, so Gradle has no way to notice that an edit
   to a file in `tools/web-overlay` has not been re-run through the generator — it
   would happily package yesterday's assets, and there is no device on this
   machine to catch that.

   So the build checks. Deliberately a warning rather than a hard failure: a
   stale asset is a mistake, but refusing to compile over it would make the build
   hostage to a Node script, and `build-web-assets.mjs` itself is the thing that
   has to run.

   (Do not write a glob like `web-overlay/<star>` anywhere in this comment: Kotlin
   block comments NEST, unlike C's, so that two-character sequence opens a second
   level and the single closing marker below only brings it back to the first —
   silently commenting out the rest of this file. That is what ate this task the
   first time it was written.)
   ========================================================================== */
val overlayDir = rootProject.file("tools/web-overlay")
val assetsDir = file("src/main/assets/web")
val generator = rootProject.file("tools/build-web-assets.mjs")

tasks.register("checkWebAssetsFreshness") {
    group = "verification"
    description = "警告：叠加层或生成脚本比 APK 里的影片新（忘了跑 build-web-assets.mjs）"

    val overlay = overlayDir
    val assets = assetsDir
    val gen = generator
    val marker = File(assets, "build-manifest.json")

    /* Read lazily, at execution time: registering a task must not touch disks. */
    onlyIf { overlay.isDirectory && marker.isFile }

    doLast {
        val newest = (overlay.listFiles() ?: emptyArray())
            .filter { it.isFile }
            .plus(gen)
            .filter { it.isFile }
            .maxByOrNull { it.lastModified() }
        if (newest != null && newest.lastModified() > marker.lastModified()) {
            logger.warn(
                "\n[warn] tools/web-overlay/${newest.name} is newer than " +
                    "app/src/main/assets/web/build-manifest.json.\n" +
                    "[warn] The APK will ship the PREVIOUS overlay. Run:\n" +
                    "[warn]     node tools/build-web-assets.mjs\n",
            )
        }
    }
}

tasks.matching { it.name == "preDebugBuild" || it.name == "preReleaseBuild" }
    .configureEach { dependsOn("checkWebAssetsFreshness") }
